In [208]:
%load_ext autoreload
%autoreload 2

import numpy as np
import matplotlib.pyplot as plt
import sys
import os
import pickle
from sklearn.preprocessing import MinMaxScaler

sys.path.append('../')
from third_party.HDCmodel import *
from conformal_inference.models import *
from conformal_inference.methods import *
from conformal_inference.utils import *

The autoreload extension is already loaded. To reload it, use:
  %reload_ext autoreload

In [247]:
class ConformalHDC():
    def __init__(self, inputs, labels, calib_size=0.2, 
                 dimension=10000, epochs=2, total_level=100,
                 sim_measure="cosine",
                 random_state=0, verbose=True, progress=True):

        self.calib_size = calib_size
        self.sim_measure = sim_measure

        self.random_state = random_state
        self.verbose = verbose
        self.progress= progress 

        inputs_train, inputs_calib, labels_train, labels_calib =\
        train_test_split(inputs, labels, test_size=self.calib_size, random_state=self.random_state)

        # Train the HD model
        HDC = HyperDimensionalComputing(dimension, totalPos = inputs_train.shape[1], totalLevel = total_level, datatype = np.int16, buffer = [-1.0, 1.0], cuda = False)
        labels_train, labels_calib = genLabel(labels_train), genLabel(labels_calib)
        classHV = dict([(x, np.array([0 for _ in range(dimension)])) for x in range(1, len(np.unique(labels_train)) + 1)])
        baseVector = HDC.genBaseVector(HDC.P, -1, HDC.dim)
        levelVector = HDC.genLevelVector(HDC.Q, -1, HDC.dim)
        
        HVector = HV_encoding(HDC, baseVector, levelVector, inputs_train)
        HVector_calib = HV_encoding(HDC, baseVector, levelVector, inputs_calib)
        self.classHVs = HDC.genClassHV(classHV, labels_train, HVector)
        self.classHVs, _ = HDC.oneShotTraining(self.classHVs, HVector, labels_train, HVector, labels_train)
        self.classHVs, _, _, _ = HDC.retraining(self.classHVs, HVector, labels_train, HVector, labels_train, epochs)

        # store model for future use
        self.HDC = HDC
        self.baseVector = baseVector
        self.levelVector = levelVector
        self.labels = np.unique(labels)
    
        # Compute the calibration scores
        self.scores_calib = {}
        scores_calib = self._compute_similarity_scores(HVector_calib, labels_calib)

        for i, label in enumerate(labels_calib):
            if (label in self.scores_calib.keys()):
                self.scores_calib[label].append(scores_calib[i])
            else:
                self.scores_calib[label] = [scores_calib[i]]

    
    
    # implement the encoding functions and other similarity scores later below 


    def _compute_similarity_scores(self, HVs, labels):
        ''' Computes the similarity scores of the HVs and corresponding classHVs
        '''

        classHVs_batch =  np.array([self.classHVs[label] for label in labels])

        if self.sim_measure == "euclidean":
            scores = np.linalg.norm(HVs - classHVs_batch, axis=1)
        elif self.sim_measure == "cosine":
            # Compute the dot product for each pair of vectors
            dot_product = np.einsum('ij,ij->i', HVs, classHVs_batch)
            norm_HV1 = np.linalg.norm(HVs, axis=1)
            norm_HV2 = np.linalg.norm(classHVs_batch, axis=1)
            scores = -dot_product / (norm_HV1 * norm_HV2 + 1e-10)
        return scores


    def predict(self, inputs_test):
        scores = []
        n_test = len(inputs_test)
        for label in self.labels:
            tmp_scores = self._compute_similarity_scores(inputs_test, [label]*n_test).reshape(-1,1)
            scores.append(tmp_scores)
        
        scores = np.concatenate(scores,axis=1)
        # if self.sim_measure == "euclidean":
        #     predicted_indices = np.argmin(scores, axis=1)
        # elif self.sim_measute == "cosine":
        #     predicted_indices = np.argmax(scores, axis=1)
        predicted_indices = np.argmin(scores, axis=1)
        predictions = [self.labels[idx] for idx in predicted_indices]

        return predictions


    def conformalPS(self, inputs_test, alpha, allow_empty=False):
        ''' Computes the conformal prediction sets at significance level alpha
        '''
        n_test = len(inputs_test)
        inputs_test = HV_encoding(self.HDC, self.baseVector, self.levelVector, inputs_test)
        self.quantiles = {}

        psets = psets = [[] for _ in range(n_test)] 
        for label in self.labels:
            n_calib = len(self.scores_calib[label])
            scores = self._compute_similarity_scores(inputs_test, [label]*n_test).reshape(-1,1)
            quantile = np.quantile(self.scores_calib[label], (n_calib+1)*(1-alpha)/n_calib)
            self.quantiles[label] = quantile

            for i in range(n_test):
                if scores[i] < quantile:
                    psets[i].append(label)
        
        if not allow_empty:
            pred = self.predict(inputs_test)
            for i, pset in enumerate(psets):
                if len(pset)==0:
                    pset.append(pred[i])

        return psets

In [300]:
def run_experiment(random_state):
    base_path="C:/Users/liang/Documents/GitHub/conformalHDC/data/CTG"
    df= pd.read_csv(os.path.join(base_path, 'cleaned_data.csv'))
    X = np.array(df.drop(columns=['Label']))
    y = np.array(df['Label'], dtype=int)

    X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.1, random_state=random_state)
    np.random.seed(random_state)
    
    # benchmark
    dimension = 10000
    epochs = 4
    HDC = HyperDimensionalComputing(dimension, totalPos = X_train.shape[1], totalLevel = 100, datatype = np.int16, buffer = [-1.0, 1.0], cuda = False)
    labels_train, labels_test = genLabel(y_train), genLabel(y_test)
    classHV = dict([(x, np.array([0 for _ in range(dimension)])) for x in range(1, len(np.unique(labels_train)) + 1)])
    baseVector = HDC.genBaseVector(HDC.P, -1, HDC.dim)
    levelVector = HDC.genLevelVector(HDC.Q, -1, HDC.dim)
    
    HVector = HV_encoding(HDC, baseVector, levelVector, X_train)
    HVector_test = HV_encoding(HDC, baseVector, levelVector, X_test)
    classHVs = HDC.genClassHV(classHV, labels_train, HVector)
    classHVs, _ = HDC.oneShotTraining(classHVs, HVector, labels_train, HVector, labels_train)
    classHVs, _, _, _ = HDC.retraining(classHVs, HVector, labels_train, HVector, labels_train, epochs)

    preds=HDC.predict(classHVs, HVector_test,labels_test)
    preds = np.array(preds).reshape(-1, 1)

    # Evaluate the predictions (hdc method)
    df_m_pred = eval_m_psets(preds, y_test)
    df_m_pred['method'] = 'HDC'
    
    df_lc_pred = eval_lc_psets(preds, y_test)
    df_lc_pred['method'] = 'HDC'

    # conformalHDC
    alpha = 0.1
    conformal = ConformalHDC(X_train, y_train, random_state=random_state, epochs=epochs, dimension=dimension, total_level=100)
    pset = conformal.conformalPS(X_test, alpha, allow_empty=True)

    # Evaluate the conformal prediction sets (conformal method)
    df_m_pset = eval_m_psets(pset, y_test)
    df_m_pset['method'] = 'conformalHDC'
    
    df_lc_pset = eval_lc_psets(pset, y_test)
    df_lc_pset['method'] = 'conformalHDC'

    # Concatenate results for this run
    result_m = pd.concat([df_m_pset, df_m_pred], ignore_index=True)
    result_lc = pd.concat([df_lc_pset, df_lc_pred], ignore_index=True)
    result_m['random_state'] = random_state
    result_lc['random_state'] = random_state
    
    return result_m, result_lc

In [307]:
# Initialize empty lists to store results
all_results_m = []
all_results_lc = []

repetitions=50
# Loop to run 50 repetitions with different random seeds
for i in tqdm(range(repetitions)):
    random_state = i
    result_m, result_lc = run_experiment(random_state)
    
    # Append the results to the list
    all_results_m.append(result_m)
    all_results_lc.append(result_lc)

# Concatenate all the results from all repetitions and variance settings
final_m_df = pd.concat(all_results_m, ignore_index=True)
final_lc_df = pd.concat(all_results_lc, ignore_index=True)

  0%|                                                                                           | 0/50 [00:00<?, ?it/s]

Epoch 1 accuracy: 93.88395190799791
Epoch 2 accuracy: 95.45216936748562
Epoch 3 accuracy: 96.44537375849451
Epoch 4 accuracy: 97.54312598013591
Epoch 1 accuracy: 94.05228758169935
Epoch 2 accuracy: 95.68627450980392
Epoch 3 accuracy: 96.5359477124183
Epoch 4 accuracy: 97.25490196078431

  2%|█▋                                                                                 | 1/50 [00:40<33:07, 40.55s/it]

Epoch 1 accuracy: 93.62258233141662
Epoch 2 accuracy: 95.71353894406691
Epoch 3 accuracy: 96.49764767381077
Epoch 4 accuracy: 97.0726607422896
Epoch 1 accuracy: 94.11764705882352
Epoch 2 accuracy: 95.68627450980392
Epoch 3 accuracy: 96.73202614379085
Epoch 4 accuracy: 97.12418300653594

  4%|███▎                                                                               | 2/50 [01:22<33:03, 41.33s/it]

Epoch 1 accuracy: 93.20439100888656
Epoch 2 accuracy: 94.98170412963931
Epoch 3 accuracy: 95.92263460533194
Epoch 4 accuracy: 96.44537375849451
Epoch 1 accuracy: 93.33333333333333
Epoch 2 accuracy: 95.81699346405229
Epoch 3 accuracy: 96.33986928104575
Epoch 4 accuracy: 97.3202614379085

  6%|████▉                                                                              | 3/50 [02:08<34:09, 43.60s/it]

Epoch 1 accuracy: 93.36121275483534
Epoch 2 accuracy: 95.71353894406691
Epoch 3 accuracy: 96.340825927862
Epoch 4 accuracy: 96.91583899634082
Epoch 1 accuracy: 93.33333333333333
Epoch 2 accuracy: 95.16339869281045
Epoch 3 accuracy: 96.20915032679738
Epoch 4 accuracy: 96.9281045751634

  8%|██████▋                                                                            | 4/50 [02:53<33:46, 44.06s/it]

Epoch 1 accuracy: 93.72713016204914
Epoch 2 accuracy: 95.45216936748562
Epoch 3 accuracy: 96.39309984317825
Epoch 4 accuracy: 97.12493465760585
Epoch 1 accuracy: 93.20261437908496
Epoch 2 accuracy: 94.90196078431372
Epoch 3 accuracy: 96.01307189542484
Epoch 4 accuracy: 97.05882352941177

 10%|████████▎                                                                          | 5/50 [03:30<31:03, 41.41s/it]

Epoch 1 accuracy: 93.15211709357031
Epoch 2 accuracy: 94.98170412963931
Epoch 3 accuracy: 96.13173026659697
Epoch 4 accuracy: 96.60219550444327
Epoch 1 accuracy: 93.98692810457516
Epoch 2 accuracy: 95.94771241830065
Epoch 3 accuracy: 97.05882352941177
Epoch 4 accuracy: 97.97385620915033

 12%|█████████▉                                                                         | 6/50 [04:20<32:33, 44.40s/it]

Epoch 1 accuracy: 93.98849973863042
Epoch 2 accuracy: 95.39989545216937
Epoch 3 accuracy: 96.60219550444327
Epoch 4 accuracy: 97.33403031887087
Epoch 1 accuracy: 93.85620915032679
Epoch 2 accuracy: 95.62091503267975
Epoch 3 accuracy: 96.9281045751634
Epoch 4 accuracy: 97.38562091503267

 14%|███████████▌                                                                       | 7/50 [05:09<32:58, 46.02s/it]

Epoch 1 accuracy: 93.41348667015158
Epoch 2 accuracy: 94.77260846837429
Epoch 3 accuracy: 96.23627809722947
Epoch 4 accuracy: 96.54992158912702
Epoch 1 accuracy: 93.52941176470588
Epoch 2 accuracy: 95.22875816993464
Epoch 3 accuracy: 96.9281045751634
Epoch 4 accuracy: 97.7124183006536

 16%|█████████████▎                                                                     | 8/50 [06:02<33:40, 48.11s/it]

Epoch 1 accuracy: 93.46576058546785
Epoch 2 accuracy: 95.29534762153685
Epoch 3 accuracy: 96.49764767381077
Epoch 4 accuracy: 97.17720857292211
Epoch 1 accuracy: 94.57516339869281
Epoch 2 accuracy: 95.62091503267975
Epoch 3 accuracy: 96.66666666666667
Epoch 4 accuracy: 97.51633986928104

 18%|██████████████▉                                                                    | 9/50 [06:52<33:17, 48.71s/it]

Epoch 1 accuracy: 93.46576058546785
Epoch 2 accuracy: 94.92943021432305
Epoch 3 accuracy: 95.87036069001567
Epoch 4 accuracy: 97.4385781495034
Epoch 1 accuracy: 93.85620915032679
Epoch 2 accuracy: 96.33986928104575
Epoch 3 accuracy: 97.3202614379085
Epoch 4 accuracy: 97.05882352941177

 20%|████████████████▍                                                                 | 10/50 [07:28<29:47, 44.68s/it]

Epoch 1 accuracy: 93.36121275483534
Epoch 2 accuracy: 95.13852587558809
Epoch 3 accuracy: 95.92263460533194
Epoch 4 accuracy: 96.65446941975954
Epoch 1 accuracy: 93.4640522875817
Epoch 2 accuracy: 95.42483660130719
Epoch 3 accuracy: 96.79738562091504
Epoch 4 accuracy: 96.86274509803921

 22%|██████████████████                                                                | 11/50 [08:11<28:46, 44.27s/it]

Epoch 1 accuracy: 92.94302143230529
Epoch 2 accuracy: 95.03397804495557
Epoch 3 accuracy: 96.340825927862
Epoch 4 accuracy: 96.7067433350758
Epoch 1 accuracy: 94.05228758169935
Epoch 2 accuracy: 95.55555555555556
Epoch 3 accuracy: 96.60130718954248
Epoch 4 accuracy: 96.99346405228758

 24%|███████████████████▋                                                              | 12/50 [09:00<28:53, 45.63s/it]

Epoch 1 accuracy: 93.62258233141662
Epoch 2 accuracy: 95.19079979090434
Epoch 3 accuracy: 96.86356508102457
Epoch 4 accuracy: 96.91583899634082
Epoch 1 accuracy: 94.05228758169935
Epoch 2 accuracy: 95.49019607843138
Epoch 3 accuracy: 96.27450980392157
Epoch 4 accuracy: 97.18954248366013

 26%|█████████████████████▎                                                            | 13/50 [09:52<29:20, 47.59s/it]

Epoch 1 accuracy: 94.04077365394669
Epoch 2 accuracy: 95.87036069001567
Epoch 3 accuracy: 96.60219550444327
Epoch 4 accuracy: 97.12493465760585
Epoch 1 accuracy: 94.18300653594771
Epoch 2 accuracy: 95.68627450980392
Epoch 3 accuracy: 96.40522875816994
Epoch 4 accuracy: 97.18954248366013

 28%|██████████████████████▉                                                           | 14/50 [10:32<27:10, 45.30s/it]

Epoch 1 accuracy: 93.25666492420282
Epoch 2 accuracy: 95.03397804495557
Epoch 3 accuracy: 96.28855201254574
Epoch 4 accuracy: 97.02038682697334
Epoch 1 accuracy: 93.79084967320262
Epoch 2 accuracy: 95.29411764705881
Epoch 3 accuracy: 96.20915032679738
Epoch 4 accuracy: 96.86274509803921

 30%|████████████████████████▌                                                         | 15/50 [11:09<25:00, 42.87s/it]

Epoch 1 accuracy: 93.72713016204914
Epoch 2 accuracy: 95.34762153685311
Epoch 3 accuracy: 96.39309984317825
Epoch 4 accuracy: 97.0726607422896
Epoch 1 accuracy: 93.79084967320262
Epoch 2 accuracy: 95.81699346405229
Epoch 3 accuracy: 96.5359477124183
Epoch 4 accuracy: 97.97385620915033

 32%|██████████████████████████▏                                                       | 16/50 [11:46<23:21, 41.22s/it]

Epoch 1 accuracy: 93.67485624673289
Epoch 2 accuracy: 95.03397804495557
Epoch 3 accuracy: 96.28855201254574
Epoch 4 accuracy: 97.22948248823838
Epoch 1 accuracy: 93.33333333333333
Epoch 2 accuracy: 95.81699346405229
Epoch 3 accuracy: 96.5359477124183
Epoch 4 accuracy: 96.86274509803921

 34%|███████████████████████████▉                                                      | 17/50 [12:24<22:05, 40.16s/it]

Epoch 1 accuracy: 93.88395190799791
Epoch 2 accuracy: 94.66806063774177
Epoch 3 accuracy: 96.13173026659697
Epoch 4 accuracy: 96.86356508102457
Epoch 1 accuracy: 94.77124183006535
Epoch 2 accuracy: 96.07843137254902
Epoch 3 accuracy: 97.58169934640523
Epoch 4 accuracy: 97.6470588235294

 36%|█████████████████████████████▌                                                    | 18/50 [13:00<20:48, 39.02s/it]

Epoch 1 accuracy: 93.67485624673289
Epoch 2 accuracy: 95.08625196027182
Epoch 3 accuracy: 96.340825927862
Epoch 4 accuracy: 96.86356508102457
Epoch 1 accuracy: 94.37908496732025
Epoch 2 accuracy: 96.07843137254902
Epoch 3 accuracy: 97.05882352941177
Epoch 4 accuracy: 97.51633986928104

 38%|███████████████████████████████▏                                                  | 19/50 [13:38<19:54, 38.52s/it]

Epoch 1 accuracy: 93.20439100888656
Epoch 2 accuracy: 95.08625196027182
Epoch 3 accuracy: 96.18400418191322
Epoch 4 accuracy: 96.28855201254574
Epoch 1 accuracy: 93.33333333333333
Epoch 2 accuracy: 94.77124183006535
Epoch 3 accuracy: 95.88235294117648
Epoch 4 accuracy: 96.79738562091504

 40%|████████████████████████████████▊                                                 | 20/50 [14:15<19:03, 38.13s/it]

Epoch 1 accuracy: 93.46576058546785
Epoch 2 accuracy: 95.13852587558809
Epoch 3 accuracy: 96.65446941975954
Epoch 4 accuracy: 96.96811291165707
Epoch 1 accuracy: 94.11764705882352
Epoch 2 accuracy: 95.55555555555556
Epoch 3 accuracy: 96.66666666666667
Epoch 4 accuracy: 97.97385620915033

 42%|██████████████████████████████████▍                                               | 21/50 [14:53<18:21, 37.99s/it]

Epoch 1 accuracy: 93.93622582331417
Epoch 2 accuracy: 95.34762153685311
Epoch 3 accuracy: 96.340825927862
Epoch 4 accuracy: 96.91583899634082
Epoch 1 accuracy: 93.52941176470588
Epoch 2 accuracy: 95.29411764705881
Epoch 3 accuracy: 96.33986928104575
Epoch 4 accuracy: 97.05882352941177

 44%|████████████████████████████████████                                              | 22/50 [15:29<17:30, 37.50s/it]

Epoch 1 accuracy: 93.83167799268165
Epoch 2 accuracy: 95.76581285938317
Epoch 3 accuracy: 97.0726607422896
Epoch 4 accuracy: 97.64767381076844
Epoch 1 accuracy: 93.85620915032679
Epoch 2 accuracy: 95.75163398692811
Epoch 3 accuracy: 96.79738562091504
Epoch 4 accuracy: 97.25490196078431

 46%|█████████████████████████████████████▋                                            | 23/50 [16:05<16:40, 37.04s/it]

Epoch 1 accuracy: 93.93622582331417
Epoch 2 accuracy: 95.76581285938317
Epoch 3 accuracy: 96.340825927862
Epoch 4 accuracy: 97.59539989545218
Epoch 1 accuracy: 93.66013071895425
Epoch 2 accuracy: 94.9673202614379
Epoch 3 accuracy: 96.79738562091504
Epoch 4 accuracy: 97.6470588235294

 48%|███████████████████████████████████████▎                                          | 24/50 [16:43<16:07, 37.20s/it]

Epoch 1 accuracy: 93.67485624673289
Epoch 2 accuracy: 95.71353894406691
Epoch 3 accuracy: 96.65446941975954
Epoch 4 accuracy: 97.22948248823838
Epoch 1 accuracy: 93.59477124183006
Epoch 2 accuracy: 95.42483660130719
Epoch 3 accuracy: 97.05882352941177
Epoch 4 accuracy: 97.90849673202614

 50%|█████████████████████████████████████████                                         | 25/50 [17:20<15:29, 37.17s/it]

Epoch 1 accuracy: 93.41348667015158
Epoch 2 accuracy: 95.13852587558809
Epoch 3 accuracy: 96.44537375849451
Epoch 4 accuracy: 97.0726607422896
Epoch 1 accuracy: 93.4640522875817
Epoch 2 accuracy: 95.55555555555556
Epoch 3 accuracy: 96.86274509803921
Epoch 4 accuracy: 97.7124183006536

 52%|██████████████████████████████████████████▋                                       | 26/50 [17:57<14:50, 37.11s/it]

Epoch 1 accuracy: 93.57030841610037
Epoch 2 accuracy: 95.08625196027182
Epoch 3 accuracy: 95.9749085206482
Epoch 4 accuracy: 96.91583899634082
Epoch 1 accuracy: 94.37908496732025
Epoch 2 accuracy: 95.68627450980392
Epoch 3 accuracy: 97.05882352941177
Epoch 4 accuracy: 97.6470588235294

 54%|████████████████████████████████████████████▎                                     | 27/50 [18:34<14:17, 37.29s/it]

Epoch 1 accuracy: 93.36121275483534
Epoch 2 accuracy: 95.39989545216937
Epoch 3 accuracy: 96.28855201254574
Epoch 4 accuracy: 96.86356508102457
Epoch 1 accuracy: 94.11764705882352
Epoch 2 accuracy: 95.68627450980392
Epoch 3 accuracy: 96.47058823529412
Epoch 4 accuracy: 97.6470588235294

 56%|█████████████████████████████████████████████▉                                    | 28/50 [19:12<13:43, 37.43s/it]

Epoch 1 accuracy: 93.57030841610037
Epoch 2 accuracy: 95.50444328280187
Epoch 3 accuracy: 96.18400418191322
Epoch 4 accuracy: 97.12493465760585
Epoch 1 accuracy: 93.79084967320262
Epoch 2 accuracy: 95.22875816993464
Epoch 3 accuracy: 96.47058823529412
Epoch 4 accuracy: 97.25490196078431

 58%|███████████████████████████████████████████████▌                                  | 29/50 [19:51<13:12, 37.75s/it]

Epoch 1 accuracy: 93.36121275483534
Epoch 2 accuracy: 94.72033455305802
Epoch 3 accuracy: 96.28855201254574
Epoch 4 accuracy: 96.65446941975954
Epoch 1 accuracy: 93.52941176470588
Epoch 2 accuracy: 95.29411764705881
Epoch 3 accuracy: 96.40522875816994
Epoch 4 accuracy: 97.12418300653594

 60%|█████████████████████████████████████████████████▏                                | 30/50 [20:29<12:36, 37.81s/it]

Epoch 1 accuracy: 93.77940407736538
Epoch 2 accuracy: 95.66126502875065
Epoch 3 accuracy: 95.76581285938317
Epoch 4 accuracy: 97.33403031887087
Epoch 1 accuracy: 93.92156862745098
Epoch 2 accuracy: 95.68627450980392
Epoch 3 accuracy: 96.99346405228758
Epoch 4 accuracy: 97.6470588235294

 62%|██████████████████████████████████████████████████▊                               | 31/50 [21:06<11:54, 37.63s/it]

Epoch 1 accuracy: 93.67485624673289
Epoch 2 accuracy: 95.87036069001567
Epoch 3 accuracy: 96.44537375849451
Epoch 4 accuracy: 97.49085206481965
Epoch 1 accuracy: 94.18300653594771
Epoch 2 accuracy: 95.81699346405229
Epoch 3 accuracy: 96.86274509803921
Epoch 4 accuracy: 97.90849673202614

 64%|████████████████████████████████████████████████████▍                             | 32/50 [21:44<11:19, 37.75s/it]

Epoch 1 accuracy: 93.83167799268165
Epoch 2 accuracy: 95.45216936748562
Epoch 3 accuracy: 96.28855201254574
Epoch 4 accuracy: 96.81129116570831
Epoch 1 accuracy: 94.11764705882352
Epoch 2 accuracy: 95.49019607843138
Epoch 3 accuracy: 97.12418300653594
Epoch 4 accuracy: 97.90849673202614

 66%|██████████████████████████████████████████████████████                            | 33/50 [22:22<10:43, 37.87s/it]

Epoch 1 accuracy: 93.88395190799791
Epoch 2 accuracy: 95.2430737062206
Epoch 3 accuracy: 96.340825927862
Epoch 4 accuracy: 97.49085206481965
Epoch 1 accuracy: 93.79084967320262
Epoch 2 accuracy: 95.62091503267975
Epoch 3 accuracy: 96.27450980392157
Epoch 4 accuracy: 97.38562091503267

 68%|███████████████████████████████████████████████████████▊                          | 34/50 [22:59<10:03, 37.69s/it]

Epoch 1 accuracy: 93.77940407736538
Epoch 2 accuracy: 94.72033455305802
Epoch 3 accuracy: 95.81808677469942
Epoch 4 accuracy: 96.81129116570831
Epoch 1 accuracy: 94.11764705882352
Epoch 2 accuracy: 95.29411764705881
Epoch 3 accuracy: 96.33986928104575
Epoch 4 accuracy: 97.45098039215686

 70%|█████████████████████████████████████████████████████████▍                        | 35/50 [23:38<09:29, 37.95s/it]

Epoch 1 accuracy: 93.51803450078411
Epoch 2 accuracy: 95.03397804495557
Epoch 3 accuracy: 96.02718243596445
Epoch 4 accuracy: 96.91583899634082
Epoch 1 accuracy: 94.44444444444444
Epoch 2 accuracy: 95.81699346405229
Epoch 3 accuracy: 96.99346405228758
Epoch 4 accuracy: 97.7124183006536

 72%|███████████████████████████████████████████████████████████                       | 36/50 [24:17<08:58, 38.47s/it]

Epoch 1 accuracy: 93.36121275483534
Epoch 2 accuracy: 94.82488238369054
Epoch 3 accuracy: 96.13173026659697
Epoch 4 accuracy: 96.75901725039205
Epoch 1 accuracy: 94.83660130718954
Epoch 2 accuracy: 95.75163398692811
Epoch 3 accuracy: 96.79738562091504
Epoch 4 accuracy: 97.45098039215686

 74%|████████████████████████████████████████████████████████████▋                     | 37/50 [24:56<08:21, 38.57s/it]

Epoch 1 accuracy: 94.09304756926294
Epoch 2 accuracy: 95.08625196027182
Epoch 3 accuracy: 96.02718243596445
Epoch 4 accuracy: 96.96811291165707
Epoch 1 accuracy: 94.31372549019608
Epoch 2 accuracy: 96.20915032679738
Epoch 3 accuracy: 97.18954248366013
Epoch 4 accuracy: 97.84313725490196

 76%|██████████████████████████████████████████████████████████████▎                   | 38/50 [25:34<07:39, 38.26s/it]

Epoch 1 accuracy: 93.20439100888656
Epoch 2 accuracy: 94.72033455305802
Epoch 3 accuracy: 95.9749085206482
Epoch 4 accuracy: 96.81129116570831
Epoch 1 accuracy: 94.18300653594771
Epoch 2 accuracy: 95.42483660130719
Epoch 3 accuracy: 96.86274509803921
Epoch 4 accuracy: 97.3202614379085

 78%|███████████████████████████████████████████████████████████████▉                  | 39/50 [26:14<07:08, 38.95s/it]

Epoch 1 accuracy: 93.77940407736538
Epoch 2 accuracy: 95.45216936748562
Epoch 3 accuracy: 96.54992158912702
Epoch 4 accuracy: 97.0726607422896
Epoch 1 accuracy: 94.05228758169935
Epoch 2 accuracy: 95.68627450980392
Epoch 3 accuracy: 97.25490196078431
Epoch 4 accuracy: 97.51633986928104

 80%|█████████████████████████████████████████████████████████████████▌                | 40/50 [26:54<06:30, 39.03s/it]

Epoch 1 accuracy: 93.15211709357031
Epoch 2 accuracy: 95.13852587558809
Epoch 3 accuracy: 96.13173026659697
Epoch 4 accuracy: 96.54992158912702
Epoch 1 accuracy: 94.24836601307189
Epoch 2 accuracy: 95.49019607843138
Epoch 3 accuracy: 96.99346405228758
Epoch 4 accuracy: 98.0392156862745

 82%|███████████████████████████████████████████████████████████████████▏              | 41/50 [27:34<05:54, 39.43s/it]

Epoch 1 accuracy: 93.46576058546785
Epoch 2 accuracy: 94.92943021432305
Epoch 3 accuracy: 96.02718243596445
Epoch 4 accuracy: 96.91583899634082
Epoch 1 accuracy: 93.33333333333333
Epoch 2 accuracy: 95.16339869281045
Epoch 3 accuracy: 96.20915032679738
Epoch 4 accuracy: 96.99346405228758

 84%|████████████████████████████████████████████████████████████████████▉             | 42/50 [28:13<05:15, 39.46s/it]

Epoch 1 accuracy: 94.09304756926294
Epoch 2 accuracy: 95.50444328280187
Epoch 3 accuracy: 96.75901725039205
Epoch 4 accuracy: 97.28175640355462
Epoch 1 accuracy: 93.72549019607843
Epoch 2 accuracy: 95.62091503267975
Epoch 3 accuracy: 96.14379084967321
Epoch 4 accuracy: 97.45098039215686

 86%|██████████████████████████████████████████████████████████████████████▌           | 43/50 [28:53<04:37, 39.58s/it]

Epoch 1 accuracy: 93.46576058546785
Epoch 2 accuracy: 95.39989545216937
Epoch 3 accuracy: 96.49764767381077
Epoch 4 accuracy: 96.91583899634082
Epoch 1 accuracy: 94.18300653594771
Epoch 2 accuracy: 95.68627450980392
Epoch 3 accuracy: 96.27450980392157
Epoch 4 accuracy: 97.25490196078431

 88%|████████████████████████████████████████████████████████████████████████▏         | 44/50 [29:33<03:57, 39.59s/it]

Epoch 1 accuracy: 93.67485624673289
Epoch 2 accuracy: 95.55671719811814
Epoch 3 accuracy: 96.44537375849451
Epoch 4 accuracy: 96.91583899634082
Epoch 1 accuracy: 93.4640522875817
Epoch 2 accuracy: 95.55555555555556
Epoch 3 accuracy: 96.47058823529412
Epoch 4 accuracy: 96.9281045751634

 90%|█████████████████████████████████████████████████████████████████████████▊        | 45/50 [30:12<03:17, 39.42s/it]

Epoch 1 accuracy: 93.41348667015158
Epoch 2 accuracy: 95.45216936748562
Epoch 3 accuracy: 96.02718243596445
Epoch 4 accuracy: 96.86356508102457
Epoch 1 accuracy: 93.98692810457516
Epoch 2 accuracy: 95.94771241830065
Epoch 3 accuracy: 96.79738562091504
Epoch 4 accuracy: 97.6470588235294

 92%|███████████████████████████████████████████████████████████████████████████▍      | 46/50 [30:52<02:38, 39.56s/it]

Epoch 1 accuracy: 93.25666492420282
Epoch 2 accuracy: 94.77260846837429
Epoch 3 accuracy: 95.76581285938317
Epoch 4 accuracy: 96.91583899634082
Epoch 1 accuracy: 93.66013071895425
Epoch 2 accuracy: 95.42483660130719
Epoch 3 accuracy: 96.73202614379085
Epoch 4 accuracy: 97.3202614379085

 94%|█████████████████████████████████████████████████████████████████████████████     | 47/50 [31:31<01:58, 39.50s/it]

Epoch 1 accuracy: 94.19759539989545
Epoch 2 accuracy: 95.81808677469942
Epoch 3 accuracy: 96.65446941975954
Epoch 4 accuracy: 97.64767381076844
Epoch 1 accuracy: 94.11764705882352
Epoch 2 accuracy: 95.94771241830065
Epoch 3 accuracy: 96.73202614379085
Epoch 4 accuracy: 97.3202614379085

 96%|██████████████████████████████████████████████████████████████████████████████▋   | 48/50 [32:10<01:18, 39.27s/it]

Epoch 1 accuracy: 93.46576058546785
Epoch 2 accuracy: 95.03397804495557
Epoch 3 accuracy: 96.60219550444327
Epoch 4 accuracy: 97.17720857292211
Epoch 1 accuracy: 93.0718954248366
Epoch 2 accuracy: 94.50980392156862
Epoch 3 accuracy: 96.01307189542484
Epoch 4 accuracy: 96.66666666666667

 98%|████████████████████████████████████████████████████████████████████████████████▎ | 49/50 [32:49<00:39, 39.08s/it]

Epoch 1 accuracy: 93.72713016204914
Epoch 2 accuracy: 95.66126502875065
Epoch 3 accuracy: 96.39309984317825
Epoch 4 accuracy: 97.17720857292211
Epoch 1 accuracy: 93.92156862745098
Epoch 2 accuracy: 95.68627450980392
Epoch 3 accuracy: 97.12418300653594
Epoch 4 accuracy: 97.45098039215686

100%|██████████████████████████████████████████████████████████████████████████████████| 50/50 [33:27<00:00, 40.15s/it]

In [308]:
final_m_df

    M-coverage    M-size  M-size|cov        method  random_state
0     0.873239  1.708920    1.924731  conformalHDC             0
1     0.934272  1.000000    1.000000           HDC             0
2     0.892019  1.807512    1.926316  conformalHDC             1
3     0.910798  1.000000    1.000000           HDC             1
4     0.915493  1.835681    1.933333  conformalHDC             2
..         ...       ...         ...           ...           ...
95    0.934272  1.000000    1.000000           HDC            47
96    0.896714  1.774648    1.910995  conformalHDC            48
97    0.981221  1.000000    1.000000           HDC            48
98    0.906103  1.826291    1.943005  conformalHDC            49
99    0.938967  1.000000    1.000000           HDC            49

[100 rows x 5 columns]

In [309]:
final_lc_df

,class1-LC-coverage,class1-LC-size,class1-LC-size|cov,class2-LC-coverage,class2-LC-size,class2-LC-size|cov,method,random_state
0,0.884146,1.804878,2.0,0.836735,1.387755,1.658537,conformalHDC,0
1,0.957317,1.000000,1.0,0.857143,1.000000,1.000000,HDC,0
2,0.876543,1.870370,2.0,0.941176,1.607843,1.708333,conformalHDC,1
3,0.944444,1.000000,1.0,0.803922,1.000000,1.000000,HDC,1
4,0.911765,1.905882,2.0,0.930233,1.558140,1.675000,conformalHDC,2
...,...,...,...,...,...,...,...,...
95,0.963190,1.000000,1.0,0.840000,1.000000,1.000000,HDC,47
96,0.905325,1.887574,2.0,0.863636,1.340909,1.552632,conformalHDC,48
97,0.982249,1.000000,1.0,0.977273,1.000000,1.000000,HDC,48
98,0.886228,1.856287,2.0,0.978261,1.717391,1.755556,conformalHDC,49
99,0.964072,1.000000,1.0,0.847826,1.000000,1.000000,HDC,49

In [310]:
# Define a function to calculate the standard error
def standard_error(x):
    return np.std(x, ddof=1) / np.sqrt(len(x))

# Group by 'method' and calculate mean and standard error for each relevant column
aggregated_df = final_lc_df.groupby('method').agg({
    'class1-LC-coverage': ['mean', standard_error],
    'class1-LC-size': ['mean', standard_error],
    'class1-LC-size|cov': ['mean', standard_error],
    'class2-LC-coverage': ['mean', standard_error],
    'class2-LC-size': ['mean', standard_error],
    'class2-LC-size|cov': ['mean', standard_error]
}).reset_index()

# Rename columns for clarity
aggregated_df.columns = ['_'.join(col).strip() if col[1] else col[0] for col in aggregated_df.columns.values]

print(aggregated_df)

         method  class1-LC-coverage_mean  class1-LC-coverage_standard_error  \
0           HDC                 0.965423                           0.002006
1  conformalHDC                 0.893356                           0.003585

   class1-LC-size_mean  class1-LC-size_standard_error  \
0             1.000000                       0.000000
1             1.852044                       0.006297

   class1-LC-size|cov_mean  class1-LC-size|cov_standard_error  \
0                  1.00000                           0.000000
1                  1.99972                           0.000196

   class2-LC-coverage_mean  class2-LC-coverage_standard_error  \
0                 0.846217                           0.006883
1                 0.900655                           0.007092

   class2-LC-size_mean  class2-LC-size_standard_error  \
0             1.000000                       0.000000
1             1.477099                       0.016346

   class2-LC-size|cov_mean  class2-LC-size|cov_standard_error
0                 1.000000                           0.000000
1                 1.640377                           0.013749